FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive
ENV API_HOST=0.0.0.0
ENV MCP_HOST=0.0.0.0
WORKDIR /app

# System packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    git \
    curl \
    nmap \
    nikto \
    dirb \
    gobuster \
    sqlmap \
    burpsuite \
    metasploit-framework \
    netcat-traditional \
    iputils-ping \
    dnsutils \
    whois \
    hydra \
    john \
    hashcat \
    exploitdb \
    tcpdump \
    wordlists \
    libimage-exiftool-perl \
    steghide \
    tcpflow \
    arp-scan \
    assetfinder \
    autorecon \
    certgraph \
    cloud-enum \
    cloudbrute \
    bind9-dnsutils \
    dmitry \
    eyewitness \
    findomain \
    httprobe \
    httpx-toolkit \
    ldeep \
    massdns \
    naabu \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN gzip -d /usr/share/wordlists/rockyou.txt.gz || true

# Create virtual environment
RUN python3 -m venv .venv
ENV PATH="/app/.venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app

EXPOSE 55100

# Non-root user
# RUN useradd -m kaliuser
# USER kaliuser

CMD ["sh", "-c", "python3 kali_server.py --ip ${API_HOST:-0.0.0.0} --port 55100"]
